apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynetapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynetapi
  template:
    metadata:
      labels:
        app: mynetapi
    spec:
      containers:
      - name: helloworld-dotnet
        image: mydockerhubusername/helloworld-dotnet:latest
        ports:
        - containerPort: 8080  # Should match your Dockerfile EXPOSE port

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-dotnet-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: helloworld-dotnet
