name: Build and Deploy to AKS

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Allow manual trigger from GitHub Actions UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Build Docker image
    - name: Build Docker Image
      run: docker build -t sree6303/mynetapi:latest${{ github.sha }} -f MyNetApi/Dockerfile .

    # Step 3: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Push Docker image to DockerHub
    - name: Push Docker Image
      run: docker push sree6303/mynetapi:latest${{ github.sha }} 

    # Step 5: Set up Azure CLI for AKS Deployment
    - name: Set Up Azure CLI
      uses: azure/login@v2  # Use the correct Azure setup action
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 6: Deploy to AKS using kubectl
    - name: Deploy to AKS
      run: |
        az aks get-credentials --resource-group MyNetApiResourceGroup --name MyAKSCluster
        kubectl apply -f deployment.yaml
